### ISSUE TITLE
Any Downsides to Using This?

### ISSUE THREAD

**Issue by ourichermath** [GloriousEggroll/amdgpu-pro-amf-fedora#1]
Sorry, but I can't figure out how else to ask this.  Are there any downsides to using this?  IOW, does installing it take over functions of the open source drivers baked into Fedora 35?  Or, does it just enable the hardware encoding function of the graphics card specifically when called (for instance, when running a game and recording it in OBS)?

**Comment by GloriousEggroll** [comment]
This repository does not override anything, but the amdgpu-pro vulkan drivers force the amdgpu-pro drivers to be used by default instead of the RADV mesa open source drivers. This is why the vulkan switcher mentioned in the readme is required. Other than that there are no drawbacks.
